# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a54d9c9ada2d155451e240a58c5d9550eba929221b2955a1dd7dd71f3206d4e4d645f2b8cd601f8d97dde4e5a36efc10ec92a7f8d01fda3764faaa5ddf20078

test:
  secret_key_base: 4ac7b34fb2a45dd1bb7a629dfe7b4dfa22d3bd4eaeee8b51430943c640f158af060ec7fec4a6b0ae0e1f48853cf5e6264ecee7a379f740e8661232a404422c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: 0a54d9c9ada2d155451e240a58c5d9550eba929221b2955a1dd7dd71f3206d4e4d645f2b8cd601f8d97dde4e5a36efc10ec92a7f8d01fda3764faaa5ddf20078
  elevennote_api_base: localhost:3000/api/v1/
  elevennote_api_key: $2a$10$nweqmq4wAAfnPTe.mILRzubq7cTtIt5MEcF7ye121qgYXYN/n/nr6
